<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Title>Spectre.Console Extensions</Title>
    <Description>This is a fork of the original Spectre.Console Extensions. This package contains some extensions for the Spectre.Console project, such as CommandAppBuilder and DependencyInjection implementation</Description>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>SpectreConsole.Extensions.Net8</PackageId>
    <Authors>Alberto Mori, michael.dgg.2</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.0.0</Version>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/michaeldgg2/Spectre.Console.Extensions</RepositoryUrl>
    <PackageTags>spectreconsole;dotnet;dependency injection</PackageTags>
    <PackageProjectUrl>https://github.com/michaeldgg2/Spectre.Console.Extensions</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
